### ISSUE TITLE
Failed to create chat in the app (local)

### ISSUE THREAD

**Issue by lemorage** [LemonNekoGH/flow-chat#37]
I installed all the dependencies, following the setup instructions in README. After I ran `pnpm dev`, and tried to create a conversation in the chat app, the following error showed up: **Failed to create chat**.

https://github.com/LemonNekoGH/flow-chat/blob/195aba6861ec20d5ef48de2f44f99f0f377065ad/src/components/RoomSelector.vue#L84-L98

I found this might be something wrong with the above code snippet, so I modified the catch clause to make it show more details, by changing it to ``toast.error(`Failed to create chat: ${error.message}`)``. I then got to see:

<code>Failed to create chat: Failed to fetch dynamically imported module: http://localhost:3333/node_modules/.pnpm/@proj-airi+duckdb-wasm@0.4.24_drizzle-orm@0.43.1_gel@2.0.2__web-worker@1.5.0/node_modules/@proj-airi/duckdb-wasm/dist/bundles/import-url-browser.mjs?v=283dab9d</code>

I am curious why it happened, and how could I resolve this error? Thank you!

**Comment by LemonNekoGH** [comment]
Thanks for your feedback, I noticed that you created a pull request #39 , did you still receive the error now?

**Comment by lemorage** [comment]
Yep! That's the thing. I kept receiving this error, and all the conversations I created before were not shown.

But I was able to create that PR, cuz GPT suggested to me that maybe I can try to remove the installed `node_modules` and re-setup again. And it kinda worked in a way.

The thing is, it only works for one time around; By that I mean, it only works for the first time with fresh installs. But if I stop it, next time when I `pnpm dev` again, the error will show up always. This is a really weird thing, and I have no idea about it. Do u have any thoughts on why it happened?

**Comment by LemonNekoGH** [comment]
Yes this is a really weird thing, and I cannot reproduce it, can you share your environment via `npx envinfo --system --binaries --browsers`

**Comment by lemorage** [comment]
Thanks for taking time on this, here is all the info:
```yaml
  System:
    OS: macOS 15.4.1
    CPU: (8) arm64 Apple M1
    Memory: 360.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 10.9.2 - /opt/homebrew/bin/npm
    pnpm: 10.11.0 - /opt/homebrew/bin/pnpm
    bun: 1.2.12 - ~/.bun/bin/bun
  Browsers:
    Chrome: 136.0.7103.114
    Chrome Canary: 138.0.7182.2
    Safari: 18.4
```
